### ISSUE TITLE
NetworkType 咨询

### ISSUE THREAD

**Issue by superorange** [shareven/wallet_hd#10]
![image](https://user-images.githubusercontent.com/49134865/143798355-39e5017a-4077-4060-a698-2d57b745c4b3.png)
作者你好，请问这个networktype里面的各个参数代表什么意思呢，为什么eth链就是数字1，这个的作用是什么呢？谷歌没找到相关资料，请指点迷津，不胜感激

**Comment by shareven** [comment]
你应该去[bitcoin_flutter](https://pub.flutter-io.cn/packages/bitcoin_flutter)提问
