### ISSUE TITLE
如何实现BTC隔离见证地址的交易签名

### ISSUE THREAD

**Issue by JackCoder2025** [shareven/wallet_hd#11]
请问下大佬如何实现BTC隔离见证类型地址的签名，目前例子只支持 P2PKH 类型地址的签名。P2SH,P2WPKH 这两种类型的地址签名，大佬能否提供一下，不胜感激。

**Comment by shareven** [comment]
可以去看一下[bitcoin_flutter](https://pub.flutter-io.cn/packages/bitcoin_flutter)的代码
