### ISSUE TITLE
是否有计划增加波场的HD钱包

### ISSUE THREAD

**Issue by yibo7** [shareven/wallet_hd#4]
非常感谢，不知道作者有没有计划增加波场的HD，这样就更加完美了，因为现在ETH的矿工费太高 ，USDT多数还是喜欢使用TRC20

**Comment by shareven** [comment]
要等有空了再来，感谢你的提议

**Comment by salemalem** [comment]
Hey guys, I don't speak Chinese but I used a translation app. Yes, that would be great if TRON was supported!!
