### ISSUE TITLE
unspent 交易如何确认

### ISSUE THREAD

**Issue by Nerogee** [shareven/wallet_hd#5]
你好，我想请教一下这个library里面可以直接抓取unspandList （unspentList） 和pengdingList 吗？在你的例子中，unspandList 和pengdingList都是hardcode 在里面的。 在实际操作过程中， 我要怎样做呢？ 谢谢你

**Comment by shareven** [comment]
1.连接节点，从链上获取。2.用第三方服务，从第三方服务那获取。（我是用的第2种方法，用的是[tokenview的服务](https://documenter.getpostman.com/view/5728777/RzZ6HfX2?version=latest#9af9fc66-5577-4326-9f50-814923241bc2)）

**Comment by neroaCu** [comment]
谢谢你shareven。

**Comment by Nerogee** [comment]
谢谢你shareven
